const getHeaderImage = (name) => {

  var name2img = {
        'BTC': require('../assets/images/coin/BTC.png'),
        'ETH': require('../assets/images/coin/ETH.png'),
        'XRP': require('../assets/images/coin/XRP.png'),    
        'QTUM':require('../assets/images/coin/QTUM.png'),
        'BTG': require('../assets/images/coin/BTG.png'),
        'EOS': require('../assets/images/coin/EOS.png'),
        'XMR': require('../assets/images/coin/XMR.png'),
        'ZEC': require('../assets/images/coin/ZEC.png'),
        'DASH':require('../assets/images/coin/DASH.png'),
        'LTC': require('../assets/images/coin/LTC.png'),
        'BCH': require('../assets/images/coin/BCH.png'),      
        'ETC': require('../assets/images/coin/ETC.png'),              
        'IOTA':require('../assets/images/coin/IOTA.png'),      
        'ICX': require('../assets/images/coin/ICX.png'),     
        'VEN': require('../assets/images/coin/VEN.png'),     
        'TRX': require('../assets/images/coin/TRX.png'),    
        'ELF': require('../assets/images/coin/ELF.png'),      
        'MITH':require('../assets/images/coin/MITH.png'),    
        'OMG': require('../assets/images/coin/OMG.png'),
        'MCO': require('../assets/images/coin/MCO.png'),
        'KNC': require('../assets/images/coin/KNC.png'),
        'GNT': require('../assets/images/coin/GNT.png'),
        'IGNIS': require('../assets/images/coin/IGNIS.png'),
        'ONT': require('../assets/images/coin/ONT.png'),
        'STORJ': require('../assets/images/coin/STORJ.png'),
        'REP': require('../assets/images/coin/REP.png'),
        'BCC': require('../assets/images/coin/BCC.png'),
        'ARDR': require('../assets/images/coin/ARDR.png'),
        'ADA': require('../assets/images/coin/ADA.png'),
        'MTL': require('../assets/images/coin/MTL.png'),
        'XEM': require('../assets/images/coin/XEM.png'),
        'VTC': require('../assets/images/coin/VTC.png'),
        'GRS': require('../assets/images/coin/GRS.png'),
        'NEO': require('../assets/images/coin/NEO.png'),
        'WAVES': require('../assets/images/coin/WAVES.png'),
        'ARK': require('../assets/images/coin/ARK.png'),
        'XLM': require('../assets/images/coin/XLM.png'),
        'STRAT': require('../assets/images/coin/STRAT.png'),
        'LSK': require('../assets/images/coin/LSK.png'),
        'EMC2': require('../assets/images/coin/EMC2.png'),
        'POWR': require('../assets/images/coin/POWR.png'),
        'SNT': require('../assets/images/coin/SNT.png'),
        'PIVX': require('../assets/images/coin/PIVX.png'),
        'SC': require('../assets/images/coin/SC.png'),
        'KMD': require('../assets/images/coin/KMD.png'),
        'MER': require('../assets/images/coin/MER.png'),
        'SBD': require('../assets/images/coin/SBD.png'),
        'STEEM': require('../assets/images/coin/STEEM.png'),
        'STORM': require('../assets/images/coin/STORM.png'),
        'TIX': require('../assets/images/coin/TIX.png'),
        'GTO': require('../assets/images/coin/GTO.png'),
  }
 
  return name2img[name];
}

export default getHeaderImage