const translate2Origin = (name) => {

  var short2Origin = {
       'BTC': 'Bitcoin',
       'ETH': 'Ethereum',
       'XRP': 'Ripple',
       'QTUM': 'Quantum',
       'BTG': 'Bitcoin Gold',
       'EOS': 'Eos',
       'XMR': 'Monero',
       'ZEC': 'Zcash',
       'DASH': 'Dash', 
       'LTC': 'Litecoin',
       'BCH': 'Bitcoin Cash',
       'ETC': 'Ethereum Classic',
       'IOTA': 'Iota',
       'ICX': 'Icon',
       'VEN': 'VeChain',
       'TRX': 'Tron',
       'ELF': 'Aelf',
       'MITH': 'Mithril',
       'OMG': 'OmiseGO',
       'MCO': 'Monaco',
       'KNC': 'Kyber Network', 
       'GNT': 'Golem',
       'IGNIS': 'Ignis',
       'ONT': 'Ontology',
       'STORJ': 'Storj',
       'REP': 'Augur',
       'BCC': 'BitConnect',
       'ARDR': 'Ardor',
       'ADA': 'Cardano',
       'MTL': 'Metal',
       'XEM': 'NEM',
       'VTC': 'Vertcoin',
       'GRS': 'Groestlcoin',
       'NEO': 'NEO',
       'WAVES': 'Waves',
       'ARK': 'Ark',
       'XLM': 'Stellar',
       'STRAT': 'Stratis ',
       'LSK': 'Lisk',
       'EMC2': 'Einsteinium',
       'POWR': 'Power Ledger',
       'SNT': 'Status',
       'PIVX': 'PIVX',
       'SC': 'Siacoin',
       'KMD': 'Komodo',
       'MER': 'Mercury',
       'SBD': 'Steem Dollars',
       'STEEM': 'Steem',
       'STORM': 'Storm',
       'TIX': 'Blocktix',
       'GTO': 'Gifto',
  }
 
  return short2Origin[name];
}

export default translate2Origin